In [ ]:
#1. What is a Python library? Why do we use Python libraries?

'''
    -Python Libraries:
    - Python libraries is a collection of prewritten code and functions that can be imported to use in our python programme.
    - Python Libraries are set functions of classes which contains some special operations functions for a specific concept like visualisation, 
       chatting, scrapping,data manipulation, scientific computing, machine learning, etc.
    - So for every concept python has specific package, and by using the functions of that package that specific operation can be performed.
      like NumPy for numerical computing, pandas for data analysis, Matplotlib for data visualization, etc.
    - Python has vast collection of packages.
    - And the packages is a class of set of functions.
    - This packages addon some extra functionalities to a a basic python language.
    - So to use these packages, we simply have to import that packages in our main programme.
       e.g. import numpy.
    - So these packages are very simple and convinient and user friendly to use in our peogramme. Developers doesnt need to code for a specific task
      where the python libraries allows developers to use a prewritten and tested code.
      Which increase the speed of developement process.
    - These libraries are open source due to which the developers doesnt hesitate to use it.
    

'''


In [ ]:
# 2. What is the difference between Numpy array and List?

'''
   Numpy Array:
   
   - The array is a collection of a homogenious elements. Which contains only one type of values.
   - The array is a always a one dimensional array but the Numpy array is a set of multiple arrays.
     So thats why the numpy array always has more than one dimensions. means minimum it can have 2 dimension.
   - So the numpy array is also considered as a matrix.
   - The numpy array is a mutable.
   - As it is homoenious, Numpy array is more memory efficient and faster than list for numerical operation.
   - NumPy arrays have a more compact internal representation compared to lists.
   - NumPy provides a wide range of mathematical functions and operations that can be applied 
     directly to arrays, making it convenient for numerical computing.
   
   
   
   List:
   
   - The list is a collection of non homogenious or heterogenious collection of element.
     Which can contain any type of value.
   - And the list is always in one dimensional.
   - The list is Mutable
   - The list is also considered as a array depending opon situation and values enclosed in it.
   - List is less optimized and can be slower for large scale numerical operations.
   - Lists have more memory overhead due to their flexible and dynamic nature.
   - Lists offer a more general set of functionalities, as they are not specialized 
     for numerical operations. However, Python provides various built-in functions and libraries that can be used with lists.

'''










In [3]:
#3. Find the shape, size and dimension of the following array?
''' 
[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]'''


import numpy as np

a = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]

print("Shape = ",np.shape(a))
print("Size = ",np.size(a))

Shape =  (3, 4)
Size =  12


In [4]:
# 4. Write python code to access the first row of the following array?
''' 
[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]'''


import numpy as np

b = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]

print(b[0])

[1, 2, 3, 4]


In [12]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?

''' 
[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]'''

#use the row index in sqr braces and anpther square breaces use column index.



import numpy as np

c = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]

print(c[2][3])





12


In [1]:
#6. Write code to extract all odd-indexed elements from the given numpy array?
''' 
[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]'''



import numpy as np

d = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]

oddIndexedElement = []

for i in range(len(d)):
    for j in range(len(d[i])):
        if (i%2!=0) and (j%2!=0):
            oddIndexedElement.append(d[i][j])
            
            
print(oddIndexedElement)            
# This returns the odd row and odd column values.            
    





[6, 8]


In [4]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?


import numpy as np

e = np.random.rand(3,3)
print(e)




[[0.49164663 0.938999   0.66954288]
 [0.88583336 0.2784492  0.52608854]
 [0.24568991 0.93097504 0.58487539]]


In [12]:
#8. Describe the difference between np.random.rand and np.random.randn?

'''
    random.rand():
    
    - This function generates a random values from a uniform distrubution in a  half open interval 
      [0.0,1.0]
    - The values will be floates which will be uniformly distributed 0 and 1.
    - This function generates a random values between 0 and 1. in a form of given shape
    
    
    random.randn():
    
    - This function generates a random numbers from standard normal distribution with mean=0 and deviation=1,
    - The returned values are floats that follow a normal (Gaussian) distribution with a mean of 0 and a standard deviation of 1.
    - This function generates an array of the specified shape with random values following a standard normal distribution.
      
      
'''
import numpy as np

e = np.random.rand(3,4)
print(e,"\n")

f = np.random.randn(5,4)
print(f)



[[0.49557308 0.12420487 0.65793334 0.82391431]
 [0.83383507 0.44691067 0.98718565 0.46874649]
 [0.94471986 0.51170955 0.39879884 0.63638633]] 

[[-0.46641447  0.37868953  2.09091388  0.38824534]
 [ 0.48384893 -0.94444006 -0.3145618   0.19815582]
 [ 1.68783414  0.78059269  0.7853824  -1.98199085]
 [-0.25920872 -2.23970466 -0.74394677  0.15746553]
 [-0.21565993  0.08106081 -0.47361574  0.29744486]]


In [22]:
#9. Write code to increase the dimension of the following array?
''' 
[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]'''


import numpy as np

g = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]

print(np.shape(g)) # Before

# Increasing the dimension of row

h = np.expand_dims(g,axis=0) #Increasing the row dimension

print(np.shape(h)) 

j = np.expand_dims(g,axis = 1)
print(np.shape(j))


(3, 4)
(1, 3, 4)
(3, 1, 4)


In [26]:
#10. How to transpose the following array in NumPy?
''' 
[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]'''


import numpy as np

k = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]

k = np.expand_dims(k,axis=0)
k.T


array([[[ 1],
        [ 5],
        [ 9]],

       [[ 2],
        [ 6],
        [10]],

       [[ 3],
        [ 7],
        [11]],

       [[ 4],
        [ 8],
        [12]]])

In [49]:
# 11. Consider the following matrix:
#   Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
#   Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

#Perform the following operation using Python.

#1.Index wise multiplication.
#2.Matrix multiplication.
#3.Add both the matric
#4.Subtract matrix B from A
#5.Divide Matrix B by A.

import numpy as np

a = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]

b =  [[1, 2, 3, 4],
      [5, 6, 7, 8],
      [9, 10, 11, 12]]

matrix_A = np.array(a)
matrix_B = np.array(b)

print("Matrix_A: \n",matrix_A,"\n\n""Matrix_B: \n",matrix_B)


#Indexed wise Multiplication
multiMatrix = matrix_A * matrix_B
print("\nMultiplication by indexed : \n",multiMatrix)


# Matrix Multipliction
sqrmatrix_1 = matrix_A[0:3,0:3]   #For  matrix multiplication the shape of each matrix should be square.
sqrmatrix_2 = matrix_B[0:3,0:3]
print("\nsqrmatrix_1: \n",sqrmatrix_1,"\n\n""sqrmatrix_2: \n",sqrmatrix_2)

matricsMultiplication = sqrmatrix_1 @ sqrmatrix_2
print("\nMatrix Multiplication matrix : \n",matricsMultiplication)

#.Add both the matric
add_Matrix = matrix_A + matrix_B
print("\nAddition matrix : \n",add_Matrix)


#Subtract matrix B from A
sub_Matrix = matrix_B - matrix_A
print("\nSubstraction matrix : \n",sub_Matrix)

#.Divide Matrix B by A.
div_Matrix = matrix_B / matrix_A
print("\nDividation matrix : \n",div_Matrix)



Matrix_A: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Matrix_B: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Multiplication by indexed : 
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

sqrmatrix_1: 
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]] 

sqrmatrix_2: 
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

Matrix Multiplication matrix : 
 [[ 38  44  50]
 [ 98 116 134]
 [158 188 218]]

Addition matrix : 
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Substraction matrix : 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Dividation matrix : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [55]:
#12. Which function in Numpy can be used to swap the byte order of an array?


# the byteswap() function is used to swap the byte order of an array

import numpy as np


original_array = np.array([1, 2, 3, 4])
print("Original array:", original_array)


swapped_array = original_array.byteswap()
print("Swapped array:", swapped_array)







Original array: [1 2 3 4]
Swapped array: [ 72057594037927936 144115188075855872 216172782113783808
 288230376151711744]


In [71]:
#13.  What is the significance of the np.linalg.inv function?

# Here lin (linear) + alg (algebra) = linalg
# and the inv = inverse 

# So basically this function returns the inverse of matrix
# so a is array and the inverse of array is denoted by a^(-1). and the indentity matrix will be a.a^(-1).


#suppose:
import numpy as np

arr = np.array([[1,2],[3,4]])

inversearr = np.linalg.inv(arr)

print("Original Array : \n",arr)
print("Inverse Array : \n",inversearr)

# Inverse indentity 
print("Inverse Identity : \n",arr*inversearr)


Original Array : 
 [[1 2]
 [3 4]]
Inverse Array : 
 [[-2.   1. ]
 [ 1.5 -0.5]]
Inverse Identity : 
 [[-2.   2. ]
 [ 4.5 -2. ]]


In [68]:
#14. What does the np.reshape function do, and how is it used?

# The np.reshape function in NumPy is used to change the shape of an array without changing its data. 
# It returns a new array with the same data but a different shape.


import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])


reshaped_array = np.reshape(original_array, (2, 3))

print("Original Array:\n",original_array)


print("\nReshaped Array:\n",reshaped_array)




Original Array:
 [1 2 3 4 5 6]

Reshaped Array:
 [[1 2 3]
 [4 5 6]]


In [70]:
#15. What is broadcasting in Numpy?

# Broadcasting in numpy is powerful mechanism which allows perform the operation between two matrix of different shapes. 
# That performs the operations elementwise.


import numpy as np


matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6]])



row_addition = np.array([10, 20, 30])

result = matrix_A + row_addition

print("Matrix A:")
print(matrix_A)

print("\nRow Addition:")
print(row_addition)

print("\nResult after Broadcasting:")
print(result)




Matrix A:
[[1 2 3]
 [4 5 6]]

Row Addition:
[10 20 30]

Result after Broadcasting:
[[11 22 33]
 [14 25 36]]
